arenas:
  testArena:
    world: world
    name: Test
    author: TechnoBrony
    spawnLocations:
      - 0 70 0
      - 10 70 10
kits:
  testKit:
    name: TestKit
    items:
      - STONE 64
      - DIAMOND_SWORD 1